/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-08-29 03:26:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Create Account</title>\n");
      out.write("\n");
      out.write("<style  type=\"text/css\">\n");
      out.write("\n");
      out.write("#content { position: relative;}\n");
      out.write("\n");
      out.write("#login {\n");
      out.write("\tposition: relative;\n");
      out.write("\ttop: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".align-right {\n");
      out.write("\ttext-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("\tborder: 1px solid gray;\n");
      out.write("\tpadding: 20px;\n");
      out.write("\tbackground-color: #CCCCFF;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".message {\n");
      out.write("\tfont-size: 16px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tfont-color: red;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<center>\n");
      out.write("\n");
      out.write("<div id=\"login\">\n");
      out.write("\n");
      out.write("<h3>New Account</h3>\n");
      out.write("\n");
      out.write("<form method=\"post\" action=\"");
      out.print( response.encodeUrl(request.getContextPath() + "/Controller?action=createaccount") );
      out.write("\">\n");
      out.write("\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"createAccount\" />\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("\n");
      out.write("<tr><td class=\"align-right\">Email address: </td><td><input type=\"text\" name=\"email\" value=\"");
      out.print( request.getAttribute("email") );
      out.write("\"/></td></tr>\n");
      out.write("<tr><td class=\"align-right\">Password: </td><td><input type=\"password\" name=\"password\" value=\"\"/></td></tr>\n");
      out.write("<tr><td class=\"align-right\">Repeat password: </td><td><input type=\"password\" name=\"repeatpassword\" value=\"\"/></td></tr>\n");
      out.write("<tr><td class=\"align-right\" colspan=\"2\"><input type=\"submit\" value=\"Log in\"/></td></tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<p class=\"message\">");
      out.print( request.getAttribute("message") );
      out.write("</p>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
